# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.landrush.enabled = true
  config.landrush.tld = 'bones.fish'
  config.landrush.host 'bare.bones.fish', '172.28.128.42'

  config.vm.box = "EliasGoldberg/centos7"

  config.vm.define "ulna" do |ulna|
    ulna.vm.network "private_network", type: "static", ip: "172.28.128.3"
    ulna.vm.hostname = "ulna.bones.fish"
    ulna.vm.provision "shell", path: "scripts/haproxy.sh"
    ulna.vm.provision "shell", path: "scripts/keepalived.sh",
    args: ["MASTER","101","172.28.128.3","172.28.128.4"]
  end

  config.vm.define "incus" do |incus|
    incus.vm.network "private_network", type: "static", ip: "172.28.128.4"
    incus.vm.hostname = "incus.bones.fish"
    incus.vm.provision "shell", path: "scripts/haproxy.sh"
    incus.vm.provision "shell", path: "scripts/keepalived.sh",
    args: ["BACKUP","100","172.28.128.4","172.28.128.3"]
  end

  config.vm.define "vomer" do |vomer|
    vomer.vm.network "private_network", type: "static", ip: "172.28.128.5"
    vomer.vm.hostname = "vomer.bones.fish"
    vomer.vm.provision "shell", path: "scripts/node.sh"
    vomer.vm.provision "shell", path: "scripts/nginx.sh"
    vomer.vm.synced_folder "../src/express", "/srv/website/express"
    vomer.vm.synced_folder "../src/nginx", "/srv/website/nginx"
  end

  config.vm.define "lunate" do |lunate|
    lunate.vm.network "private_network", type: "static", ip: "172.28.128.6"
    lunate.vm.hostname = "lunate.bones.fish"
    lunate.vm.provision "shell", path: "scripts/node.sh"
    lunate.vm.provision "shell", path: "scripts/nginx.sh"
    lunate.vm.synced_folder "../src/express", "/srv/website/express"
    lunate.vm.synced_folder "../src/nginx", "/srv/website/nginx"
  end

  config.vm.provision "shell", inline: <<-SHELL

  SHELL
end
